useTabs: true
singleQuote: true
trailingComma: es5
singleAttributePerLine: false
printWidth: 100
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
